import type { DocumentReference, Firestore } from 'firebase-admin/firestore';
import { paths } from '../../packages/shared/src/paths.js';
import { connectionRequest, connectionRespond } from '../../functions/src/commands/connection.js';
import { mappingCreate } from '../../functions/src/commands/mapping.js';
import { orgCreate } from '../../functions/src/commands/org.js';
import { partnerCatalogPublish } from '../../functions/src/commands/partner-catalog.js';
import { productCreate } from '../../functions/src/commands/product.js';
import { stockRecordOpeningBalance } from '../../functions/src/commands/stock.js';
import { teamAcceptInvitation, teamCreateInvitation } from '../../functions/src/commands/team.js';
import { CLOCK, GRAND_PRODUCTS, TEAM } from '../bootstrap/fixtures.js';
import { runCommand, seedOperationId } from './commands.js';
import type { SeedContext } from './context.js';

/**
 * The canonical command-driven seed — DB-08 §1 … §3, at **t₀**.
 *
 * Everything a command owns is built by that command: organizations, team
 * memberships, products, opening balances, the partner catalog, the connection
 * and the mapping. That is DB-08 §5's whole point — the seed itself proves that
 * `org.create`, `product.create` and `stock.recordOpeningBalance` work, that
 * every movement has a receipt, and that the ledger reconciles before a single
 * test runs.
 *
 * **Rerun safety comes from the system's own mechanism, not from a flag.** Every
 * idempotent command carries a stable {@link seedOperationId}, so a second run
 * reads the `commandReceipt`, returns the stored result and writes nothing
 * (`INV-06`). The few surfaces a **client** writes directly in production —
 * categories, the second store room, private partners, purchase-order drafts and
 * their lines — are written here only when absent, so a rerun cannot reset an
 * order that has since moved on.
 */

export interface SeedResult {
  readonly buyerOrgId: string;
  readonly supplierOrgId: string;
  readonly buyerWarehouses: { readonly main: string; readonly cold: string };
  readonly supplierWarehouseId: string;
  readonly productIds: ReadonlyMap<string, string>;
  readonly supplierProductIds: ReadonlyMap<string, string>;
  readonly connectionId: string;
  readonly catalogItemIds: ReadonlyMap<string, string>;
  readonly mappingId: string;
  readonly privatePartnerId: string;
  readonly uids: {
    readonly buyerOwner: string;
    readonly buyerInventory: string;
    readonly buyerProcurement: string;
    readonly buyerStorekeeper: string;
    readonly supplierOwner: string;
  };
}

const BUYER = {
  handle: 'grand-ocean',
  name: 'Grand Ocean Hotel',
  industry: 'Hospitality',
  country: 'LK',
  currency: 'LKR',
  timezone: 'Asia/Colombo',
} as const;

const SUPPLIER = {
  handle: 'freshfoods',
  name: 'Fresh Foods Ltd',
  industry: 'Food & Beverage',
  country: 'LK',
  currency: 'LKR',
  timezone: 'Asia/Colombo',
} as const;

const SUPPLIER_OWNER = {
  uid: 'fresh-owner',
  displayName: 'Fresh Foods Owner',
  email: 'owner@freshfoods.stockmok.test',
} as const;

const CATEGORIES = [
  ['meat', 'Meat'],
  ['dairy', 'Dairy'],
  ['dry-goods', 'Dry Goods'],
  ['beverages', 'Beverages'],
] as const;

/** DB-08 §3. No cost is stated for the supplier's own products, so none is invented. */
const SUPPLIER_PRODUCTS = [
  {
    sku: 'FF-CHK-05',
    name: 'Chicken Breast 5 KG Pack',
    categoryId: 'meat',
    unit: 'PACK',
    opening: 200,
    partnerSku: 'CKN-B5',
    packDescription: '5 KG',
  },
  {
    sku: 'FF-BTR-01',
    name: 'Butter Block 1 KG',
    categoryId: 'dairy',
    unit: 'KG',
    opening: 300,
    partnerSku: 'BTR-1K',
    packDescription: '1 KG',
  },
] as const;

export const COLD_ROOM_ID = 'cold-room';
export const GREEN_FARM_ID = 'green-farm';

/** Operation-id slots. Stable across runs, and never reused between steps. */
const SLOT = {
  buyerOrg: 1,
  supplierOrg: 2,
  invitation: 100, // + team index
  acceptance: 200, // + team index
  buyerProduct: 300, // + product index
  buyerOpening: 400, // + product index
  supplierProduct: 500, // + product index
  supplierOpening: 600, // + product index
  connectionRequest: 700,
  connectionRespond: 701,
  mapping: 702,
} as const;

async function createIfAbsent(
  ref: DocumentReference,
  data: Record<string, unknown>,
): Promise<void> {
  if ((await ref.get()).exists) return;
  await ref.set(data);
}

/**
 * The organization id is server-generated by `org.create`, so a rerun resolves
 * it from the **public directory** rather than assuming it. The handle
 * reservation would refuse a second create anyway; resolving first turns that
 * into a no-op instead of an error.
 */
interface OrganizationSpec {
  readonly handle: string;
  readonly name: string;
  readonly industry: string;
  readonly country: string;
  readonly currency: string;
  readonly timezone: string;
}

async function ensureOrganization(
  db: Firestore,
  spec: OrganizationSpec,
  owner: { uid: string; email: string },
  slot: number,
): Promise<{ orgId: string; warehouseId: string }> {
  const directory = await db.doc(paths.organizationDirectory(spec.handle)).get();
  if (directory.exists) {
    const orgId = directory.get('organizationId') as string;
    const settings = await db.doc(paths.settings(orgId)).get();
    return { orgId, warehouseId: settings.get('defaultWarehouseId') as string };
  }
  const result = await runCommand(
    orgCreate,
    {
      uid: owner.uid,
      email: owner.email,
      orgId: spec.handle,
      operationId: seedOperationId(slot),
      payload: {
        name: spec.name,
        handle: spec.handle,
        industry: spec.industry,
        country: spec.country,
        currency: spec.currency,
        timezone: spec.timezone,
      },
    },
    db,
  );
  return {
    orgId: result.organizationId as string,
    warehouseId: result.warehouseId as string,
  };
}

/** Categories are a `SAFE_DIRECT_CLIENT_WRITE` surface — no command owns them. */
async function ensureCategories(db: Firestore, orgId: string, actorUid: string): Promise<void> {
  for (const [categoryId, name] of CATEGORIES) {
    await createIfAbsent(db.doc(paths.category(orgId, categoryId)), {
      categoryId,
      name,
      status: 'ACTIVE',
      createdAt: CLOCK.t0,
      createdBy: actorUid,
      updatedAt: CLOCK.t0,
      updatedBy: actorUid,
    });
  }
}

/**
 * `org.create` makes the first store room (`Main Store`, the default). The
 * second is a client write: the catalog has `warehouse.archive`, `restore` and
 * `setDefault`, and no `warehouse.create`.
 */
async function ensureColdRoom(db: Firestore, orgId: string, actorUid: string): Promise<string> {
  await createIfAbsent(db.doc(paths.warehouse(orgId, COLD_ROOM_ID)), {
    warehouseId: COLD_ROOM_ID,
    name: 'Cold Room',
    type: 'REFRIGERATED',
    status: 'ACTIVE',
    createdAt: CLOCK.t0,
    createdBy: actorUid,
    updatedAt: CLOCK.t0,
    updatedBy: actorUid,
  });
  return COLD_ROOM_ID;
}

/** The full seven-role team, through the real invitation → acceptance path. */
async function ensureTeam(db: Firestore, orgId: string, ownerUid: string): Promise<void> {
  for (const [index, member] of TEAM.entries()) {
    if (member.role === 'OWNER') continue;
    const existing = await db.doc(paths.member(orgId, member.uid)).get();
    if (existing.exists && existing.get('status') === 'ACTIVE') continue;

    const invitation = await runCommand(
      teamCreateInvitation,
      {
        uid: ownerUid,
        orgId,
        operationId: seedOperationId(SLOT.invitation + index),
        payload: { email: member.email, role: member.role },
      },
      db,
    );
    await runCommand(
      teamAcceptInvitation,
      {
        uid: member.uid,
        email: member.email,
        orgId,
        operationId: seedOperationId(SLOT.acceptance + index),
        payload: { token: invitation.token as string },
      },
      db,
    );
    await db.doc(paths.member(orgId, member.uid)).update({ displayName: member.displayName });
  }
}

/** `product.create` generates the id; a rerun resolves it from `productSkuIndex`. */
async function ensureProduct(
  db: Firestore,
  orgId: string,
  actorUid: string,
  slot: number,
  payload: Record<string, unknown>,
): Promise<string> {
  const sku = payload.internalSku as string;
  const index = await db.doc(paths.productSkuIndex(orgId, sku)).get();
  if (index.exists) return index.get('productId') as string;
  const result = await runCommand(
    productCreate,
    { uid: actorUid, orgId, operationId: seedOperationId(slot), payload },
    db,
  );
  return result.productId as string;
}

export async function seedCanonical(context: SeedContext): Promise<SeedResult> {
  const { db } = context;
  const owner = TEAM.find((member) => member.role === 'OWNER');
  const inventory = TEAM.find((member) => member.role === 'INVENTORY_MANAGER');
  const procurement = TEAM.find((member) => member.role === 'PROCUREMENT_MANAGER');
  const storekeeper = TEAM.find((member) => member.role === 'STOREKEEPER');
  if (!owner || !inventory || !procurement || !storekeeper) {
    throw new Error('The canonical team fixture is incomplete');
  }

  // ── 1 · the two organizations ────────────────────────────────────────────
  const buyer = await ensureOrganization(db, BUYER, owner, SLOT.buyerOrg);
  const supplier = await ensureOrganization(db, SUPPLIER, SUPPLIER_OWNER, SLOT.supplierOrg);

  await ensureCategories(db, buyer.orgId, owner.uid);
  await ensureCategories(db, supplier.orgId, SUPPLIER_OWNER.uid);
  const coldRoomId = await ensureColdRoom(db, buyer.orgId, owner.uid);
  await ensureTeam(db, buyer.orgId, owner.uid);

  // ── 2 · Grand Ocean's twelve products and their opening balances ─────────
  const productIds = new Map<string, string>();
  for (const [index, product] of GRAND_PRODUCTS.entries()) {
    const minimumStockMilli = product.minimum * 1000;
    const id = await ensureProduct(db, buyer.orgId, inventory.uid, SLOT.buyerProduct + index, {
      internalSku: product.sku,
      name: product.name,
      categoryId: product.categoryId,
      baseUnit: product.unit,
      purchaseCostMinor: product.costMinor,
      currency: 'LKR',
      minimumStockMilli,
      reorderTargetMilli: Math.max(minimumStockMilli, minimumStockMilli * 2),
    });
    productIds.set(product.sku, id);

    // Cooking Oil is seeded at **zero** and still gets its movement: a product
    // with no movement and a product at zero are different facts, and the
    // out-of-stock KPI must be provable from the ledger (DB-08 §2).
    await runCommand(
      stockRecordOpeningBalance,
      {
        uid: inventory.uid,
        orgId: buyer.orgId,
        operationId: seedOperationId(SLOT.buyerOpening + index),
        payload: {
          productId: id,
          warehouseId: product.warehouseId === 'cold-room' ? coldRoomId : buyer.warehouseId,
          quantityMilli: product.opening * 1000,
          effectiveAt: CLOCK.t0,
        },
      },
      db,
    );
  }

  // ── 3 · Fresh Foods' two products, balances and partner catalog ──────────
  const supplierProductIds = new Map<string, string>();
  const catalogItemIds = new Map<string, string>();
  for (const [index, product] of SUPPLIER_PRODUCTS.entries()) {
    const id = await ensureProduct(
      db,
      supplier.orgId,
      SUPPLIER_OWNER.uid,
      SLOT.supplierProduct + index,
      {
        internalSku: product.sku,
        name: product.name,
        categoryId: product.categoryId,
        baseUnit: product.unit,
        purchaseCostMinor: 0,
        currency: 'LKR',
        minimumStockMilli: 0,
        reorderTargetMilli: 0,
      },
    );
    supplierProductIds.set(product.sku, id);

    await runCommand(
      stockRecordOpeningBalance,
      {
        uid: SUPPLIER_OWNER.uid,
        orgId: supplier.orgId,
        operationId: seedOperationId(SLOT.supplierOpening + index),
        payload: {
          productId: id,
          warehouseId: supplier.warehouseId,
          quantityMilli: product.opening * 1000,
          effectiveAt: CLOCK.t0,
        },
      },
      db,
    );

    // `partnerCatalog.publish` is NOT idempotent (DB-06 §1), so the rerun guard
    // is the frozen `partnerPublished` flag the command itself maintains.
    const productDoc = await db.doc(paths.product(supplier.orgId, id)).get();
    if (productDoc.get('partnerPublished') !== true) {
      const item = await runCommand(
        partnerCatalogPublish,
        {
          uid: SUPPLIER_OWNER.uid,
          orgId: supplier.orgId,
          payload: {
            sourceProductId: id,
            partnerSku: product.partnerSku,
            displayName: product.name,
            // INV-17 — the order unit IS the product's base unit.
            orderUnit: product.unit,
            packDescription: product.packDescription,
          },
        },
        db,
      );
      catalogItemIds.set(product.partnerSku, item.catalogItemId as string);
    } else {
      const published = await db
        .collection(`${paths.organization(supplier.orgId)}/partnerCatalog`)
        .where('sourceProductId', '==', id)
        .limit(1)
        .get();
      const existing = published.docs[0];
      if (!existing) throw new Error(`No catalog item found for ${product.sku}`);
      catalogItemIds.set(product.partnerSku, existing.id);
    }
  }

  // ── 4 · the connection, buyer → supplier ─────────────────────────────────
  const connection = await runCommand(
    connectionRequest,
    {
      uid: procurement.uid,
      orgId: buyer.orgId,
      operationId: seedOperationId(SLOT.connectionRequest),
      payload: { supplierHandle: SUPPLIER.handle },
    },
    db,
  );
  const connectionId = connection.connectionId as string;
  await runCommand(
    connectionRespond,
    {
      uid: SUPPLIER_OWNER.uid,
      orgId: supplier.orgId,
      operationId: seedOperationId(SLOT.connectionRespond),
      payload: { connectionId, response: 'ACCEPT' },
    },
    db,
  );

  // ── 5 · the mapping: 1 PACK of CKN-B5 = 5 KG of MEAT-001 ─────────────────
  const meatProductId = productIds.get('MEAT-001');
  const chickenCatalogItemId = catalogItemIds.get('CKN-B5');
  if (!meatProductId || !chickenCatalogItemId) {
    throw new Error('The canonical mapping is missing one of its two sides');
  }
  const mapping = await runCommand(
    mappingCreate,
    {
      uid: procurement.uid,
      orgId: buyer.orgId,
      operationId: seedOperationId(SLOT.mapping),
      payload: {
        connectionId,
        buyerProductId: meatProductId,
        supplierCatalogItemId: chickenCatalogItemId,
        typedPartnerSku: 'CKN-B5',
        supplierToBuyerBaseFactorMilli: 5000,
        semanticConfirmed: true,
      },
    },
    db,
  );

  // ── 6 · Green Farm Poultry, the private supplier ─────────────────────────
  await createIfAbsent(db.doc(paths.privatePartner(buyer.orgId, GREEN_FARM_ID)), {
    partnerId: GREEN_FARM_ID,
    partnerTypes: ['SUPPLIER'],
    name: 'Green Farm Poultry',
    status: 'ACTIVE',
    ordersPlacedCount: 0,
    createdAt: CLOCK.t0,
    createdBy: procurement.uid,
    updatedAt: CLOCK.t0,
    updatedBy: procurement.uid,
  });

  return {
    buyerOrgId: buyer.orgId,
    supplierOrgId: supplier.orgId,
    buyerWarehouses: { main: buyer.warehouseId, cold: coldRoomId },
    supplierWarehouseId: supplier.warehouseId,
    productIds,
    supplierProductIds,
    connectionId,
    catalogItemIds,
    mappingId: mapping.mappingId as string,
    privatePartnerId: GREEN_FARM_ID,
    uids: {
      buyerOwner: owner.uid,
      buyerInventory: inventory.uid,
      buyerProcurement: procurement.uid,
      buyerStorekeeper: storekeeper.uid,
      supplierOwner: SUPPLIER_OWNER.uid,
    },
  };
}

export { SUPPLIER_PRODUCTS, SUPPLIER_OWNER, BUYER, SUPPLIER };
