export interface AcceptanceRow {
  readonly acceptanceId: string;
  readonly sourceAuthority: string;
  readonly screenId: string;
  readonly routeId: string;
  readonly roleOrRoleClass: string;
  readonly behavior: string;
  readonly queryIds: readonly string[];
  readonly commandIds: readonly string[];
  readonly viewportRequirement: string;
  readonly evidenceType:
    'REAL_BROWSER' | 'REAL_BROWSER_REAL_EMULATOR' | 'BLOCKED_AUTHORITY_DEPENDENCY';
}

const source = {
  route: 'docs/ui-final/20_FINAL_NAVIGATION_LINK_AND_ROUTE_MAP.md',
  matrix: 'docs/frontend-execution-control-pack/04_ROUTE_SCREEN_FEATURE_MATRIX.md',
  query: 'docs/database-final/DB_04_FINAL_QUERY_INDEX_PAGINATION_REALTIME_CONTRACT.md',
  command: 'docs/frontend-execution-control-pack/08_COMMAND_AND_MUTATION_MAP.md',
  rbac: 'docs/frontend-execution-control-pack/09_ROLE_RBAC_UI_MAP.md',
} as const;

/**
 * Macro-B (F4 Network/Connected-Commerce + F5 Team/Settings/Notifications/Reports)
 * acceptance ledger. Independent from the frozen Macro-A (A10) manifest — see
 * tests/e2e/a10/acceptance-manifest.ts, which must not be modified by Macro-B work.
 */
export const macroBAcceptanceManifest: readonly AcceptanceRow[] = [
  // ─── Network ────────────────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F4-NET-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-031',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Connected Businesses lists the ACTIVE Fresh Foods connection when Network is enabled',
    queryIds: ['Q-041'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-NET-002',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A role outside NETWORK_ROLES is denied Network routes before any query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-NET-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-031/028',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Disabling Network in Settings turns Network routes into 404, not 403; re-enabling restores access',
    queryIds: ['Q-006'],
    commandIds: ['C-02'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-DISC-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery blocks searching the caller’s own handle',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-DISC-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery reports no match for an exact unknown handle (no fuzzy search)',
    queryIds: ['Q-001'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-DISC-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery finds an exact-handle match and surfaces its directory card',
    queryIds: ['Q-001'],
    commandIds: ['C-18'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CONN-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-033',
    routeId: 'ROUTE-032',
    roleOrRoleClass: 'OWNER',
    behavior: 'Connection detail renders status, direction, and disable/catalog/mapping actions',
    queryIds: ['Q-034', 'Q-042', 'Q-043'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Supplier / buyer catalog ───────────────────────────────────────────────
  {
    acceptanceId: 'MB-F4-CAT-SUP-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-034/051',
    routeId: 'ROUTE-033',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Publishing an own product to the supplier catalog projects only the allowlisted fields',
    queryIds: ['Q-045'],
    commandIds: ['C-21'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CAT-SUP-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-034',
    routeId: 'ROUTE-033',
    roleOrRoleClass: 'OWNER',
    behavior: 'Unpublishing a supplier catalog item removes it from the published list',
    queryIds: ['Q-045'],
    commandIds: ['C-22'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CAT-BUY-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-035',
    routeId: 'ROUTE-034',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Buyer catalog lists a connected supplier’s published items and finds one by exact SKU',
    queryIds: ['Q-046'],
    commandIds: ['C-24'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Product mappings ───────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F4-MAP-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-037',
    routeId: 'ROUTE-036',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Mappings list shows the VERIFIED mapping and states disabled mappings cannot be restored',
    queryIds: ['Q-043'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-MAP-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-036',
    routeId: 'ROUTE-035',
    roleOrRoleClass: 'OWNER',
    behavior: 'Mapping wizard refuses an unknown supplier SKU and an invalid conversion factor',
    queryIds: ['Q-047'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-MAP-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-036',
    routeId: 'ROUTE-035',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Mapping wizard creates a new VERIFIED mapping after semantic confirmation and a positive factor',
    queryIds: ['Q-011', 'Q-041', 'Q-047'],
    commandIds: ['C-25'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-MAP-004',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-037',
    routeId: 'ROUTE-036',
    roleOrRoleClass: 'OWNER',
    behavior: 'Disabling a mapping removes it from the active list with no restore action offered',
    queryIds: ['Q-043'],
    commandIds: ['C-26'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Connected purchase orders ──────────────────────────────────────────────
  {
    acceptanceId: 'MB-F4-CPO-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior:
      'Buyer submits an existing connected draft; C-34 line editing stays read-only throughout',
    queryIds: ['Q-036', 'Q-037', 'Q-038'],
    commandIds: ['C-27'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-002',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Buyer cancels an existing connected draft',
    queryIds: ['Q-036'],
    commandIds: ['C-31'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-003',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier accepts a SUBMITTED connected order',
    queryIds: ['Q-036'],
    commandIds: ['C-28'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-004',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier rejects a SUBMITTED connected order',
    queryIds: ['Q-036'],
    commandIds: ['C-28'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-005',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier ships an ACCEPTED order as a single full shipment',
    queryIds: ['Q-036'],
    commandIds: ['C-29'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-006',
    sourceAuthority: source.command,
    screenId: 'SCREEN-040',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior:
      'Buyer receives a SHIPPED connected order partially, then completes it, with supplier-unit conversion',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-30'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F4-CPO-007',
    sourceAuthority: source.command,
    screenId: 'SCREEN-040',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'An over-receipt beyond the outstanding supplier quantity is blocked client-side',
    queryIds: ['Q-036', 'Q-037'],
    commandIds: ['C-30'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Team ───────────────────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F5-TEAM-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-027',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Team screen protects the Owner row from role/suspend/remove actions available on other rows',
    queryIds: ['Q-009', 'Q-010'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F5-TEAM-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-027/050',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'OWNER',
    behavior: 'Owner invites a new user and the invite link is shown exactly once',
    queryIds: ['Q-009'],
    commandIds: ['C-07'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F5-TEAM-003',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-027',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A non-Owner/Admin role is denied Team before any team query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Settings ───────────────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F5-SET-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-028',
    routeId: 'ROUTE-028',
    roleOrRoleClass: 'OWNER',
    behavior: 'Owner has full Settings access including the Network feature toggle',
    queryIds: ['Q-006', 'Q-007', 'Q-017'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F5-SET-002',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-028',
    routeId: 'ROUTE-028',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A non-Owner/Admin role is denied Settings before any settings query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Notifications ──────────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F5-NOTIF-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-026',
    routeId: 'ROUTE-029',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Notifications list renders and states mark-read is temporarily unavailable (authority-blocked)',
    queryIds: ['Q-004', 'Q-005'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Reports ────────────────────────────────────────────────────────────────
  {
    acceptanceId: 'MB-F5-REPORT-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-048',
    routeId: 'ROUTE-030',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Stock-on-hand report renders with filters, category subtotals, and a desktop CSV export control',
    queryIds: ['Q-061'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-F5-REPORT-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-049',
    routeId: 'ROUTE-030',
    roleOrRoleClass: 'STOREKEEPER',
    behavior:
      'PO report renders its table for an authorized role and is denied before query for Storekeeper',
    queryIds: ['Q-062'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── 7-role RBAC boundary evidence (F4 + F5 representative surfaces) ────────
  {
    acceptanceId: 'MB-RBAC-ADMIN-001',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031/027/028',
    routeId: 'ROUTE-031/027/028',
    roleOrRoleClass: 'ADMIN',
    behavior:
      'ADMIN receives live Network (F4) access and live Team/Settings (F5) access equivalent to Owner',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-RBAC-INVENTORY_MANAGER-001',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031/040/027/028',
    routeId: 'ROUTE-031/021/027/028',
    roleOrRoleClass: 'INVENTORY_MANAGER',
    behavior:
      'INVENTORY_MANAGER is denied Network/Team/Settings before query but retains live connected-receiving access',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-RBAC-PROCUREMENT_MANAGER-001',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031/040/027/028/049',
    routeId: 'ROUTE-031/021/027/028/030',
    roleOrRoleClass: 'PROCUREMENT_MANAGER',
    behavior:
      'PROCUREMENT_MANAGER has live Network and connected-receiving access, live PO-report access, and is denied Team/Settings before query',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-RBAC-STOREKEEPER-004',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-038/040',
    routeId: 'ROUTE-019/021',
    roleOrRoleClass: 'STOREKEEPER',
    behavior:
      'STOREKEEPER retains live read access to connected purchase orders and connected receiving with mutation controls hidden',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-RBAC-ANALYST-001',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031/040/027/028/049',
    routeId: 'ROUTE-031/021/027/028/030',
    roleOrRoleClass: 'ANALYST',
    behavior:
      'ANALYST is denied Network/connected-receiving/Team/Settings before query but retains live read-only connected-PO and PO-report access',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'MB-RBAC-VIEWER-001',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031/038/040/027/028/049/048',
    routeId: 'ROUTE-031/019/021/027/028/030',
    roleOrRoleClass: 'VIEWER',
    behavior:
      'VIEWER is denied Network/connected-PO/connected-receiving/Team/Settings/PO-report before query but retains live stock report read access',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Blocked authority dependencies (not executable) ────────────────────────
  {
    acceptanceId: 'MB-F4-CPO-BLOCKED-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'F4-T03e C34 connected draft-line persistence',
    queryIds: [],
    commandIds: ['C-34'],
    viewportRequirement: '1280x900',
    evidenceType: 'BLOCKED_AUTHORITY_DEPENDENCY',
  },
  {
    acceptanceId: 'MB-F5-NOTIF-BLOCKED-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-026',
    routeId: 'ROUTE-029',
    roleOrRoleClass: 'OWNER',
    behavior: 'F5-T02 Notification mark-read',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'BLOCKED_AUTHORITY_DEPENDENCY',
  },
];

export const macroBAcceptanceIds = new Set(macroBAcceptanceManifest.map((row) => row.acceptanceId));
