/**
 * Frozen configuration for the Stockmok wide-QA dataset.
 *
 * Every value here participates in the determinism fingerprint. Changing any of
 * them changes the dataset identity, so they are constants rather than options.
 */

export const DATASET_VERSION = 'stockmok-wide-qa-v1';
export const DEFAULT_RANDOM_SEED = 20_260_824;
export const FIXTURE_EPOCH = '2026-08-01T00:00:00Z';

export type QaProfile = 'smoke' | 'wide';

export interface ProfileDefinition {
  readonly profile: QaProfile;
  /** Baseline organizations generated by the profile. */
  readonly organizationCount: number;
  /** Additional edge-case organizations generated by the profile. */
  readonly specialOrganizationCount: number;
  /**
   * Execution is an explicit gate. Wide was false until the owner-approved
   * reconciliation and green deterministic Smoke checkpoint opened it.
   */
  readonly executable: boolean;
}

export const PROFILES: Readonly<Record<QaProfile, ProfileDefinition>> = {
  smoke: {
    profile: 'smoke',
    organizationCount: 3,
    specialOrganizationCount: 0,
    executable: true,
  },
  wide: {
    profile: 'wide',
    organizationCount: 50,
    specialOrganizationCount: 6,
    executable: true,
  },
};

function isQaProfile(value: string): value is QaProfile {
  return value === 'smoke' || value === 'wide';
}

function readFlag(argv: readonly string[], flag: string): string | undefined {
  const prefix = `--${flag}=`;
  const match = argv.find((entry) => entry.startsWith(prefix));
  return match?.slice(prefix.length);
}

export function resolveProfile(argv: readonly string[] = process.argv.slice(2)): ProfileDefinition {
  const raw = readFlag(argv, 'profile') ?? 'smoke';
  if (!isQaProfile(raw)) {
    throw new Error(`Unknown QA profile "${raw}"; expected smoke or wide`);
  }
  return PROFILES[raw];
}

export function resolveSeed(argv: readonly string[] = process.argv.slice(2)): number {
  const raw = readFlag(argv, 'seed');
  if (raw === undefined) return DEFAULT_RANDOM_SEED;
  const parsed = Number(raw);
  if (!Number.isSafeInteger(parsed) || parsed < 0) {
    throw new Error(`QA seed must be a non-negative safe integer, received "${raw}"`);
  }
  return parsed;
}

/**
 * Hard gate in front of the 50+6 dataset.
 *
 * The wide profile was opened only after the owner-approved DV-12 amendment,
 * the connected-order parity repair, and two identical green Smoke cycles.
 */
export function assertProfileExecutable(definition: ProfileDefinition): void {
  if (definition.executable) return;
  throw new Error(
    `QA profile "${definition.profile}" is defined but not executable yet. ` +
      'The wide dataset stays gated until the smoke profile passes its ' +
      'generation, verification, and determinism proof.',
  );
}
