export interface AcceptanceRow {
  readonly acceptanceId: string;
  readonly sourceAuthority: string;
  readonly screenId: string;
  readonly routeId: string;
  readonly roleOrRoleClass: string;
  readonly behavior: string;
  readonly queryIds: readonly string[];
  readonly commandIds: readonly string[];
  readonly viewportRequirement: string;
  readonly evidenceType: 'REAL_BROWSER' | 'REAL_BROWSER_REAL_EMULATOR';
}

const source = {
  route: 'docs/ui-final/20_FINAL_NAVIGATION_LINK_AND_ROUTE_MAP.md',
  matrix: 'docs/frontend-execution-control-pack/04_ROUTE_SCREEN_FEATURE_MATRIX.md',
  query: 'docs/database-final/DB_04_FINAL_QUERY_INDEX_PAGINATION_REALTIME_CONTRACT.md',
  command: 'docs/frontend-execution-control-pack/08_COMMAND_AND_MUTATION_MAP.md',
  rbac: 'docs/frontend-execution-control-pack/09_ROLE_RBAC_UI_MAP.md',
  responsive: 'docs/frontend-execution-control-pack/10_RESPONSIVE_BEHAVIOR_MAP.md',
} as const;

export const acceptanceManifest: readonly AcceptanceRow[] = [
  {
    acceptanceId: 'A10-F1-001',
    sourceAuthority: source.route,
    screenId: 'SCREEN-001',
    routeId: 'ROUTE-001',
    roleOrRoleClass: 'PUBLIC',
    behavior: 'Public home renders and exposes governed auth links',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER',
  },
  {
    acceptanceId: 'A10-F1-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-003',
    routeId: 'ROUTE-003',
    roleOrRoleClass: 'ACTIVE_MEMBER',
    behavior:
      'Global login resolves membership from the authenticated UID and dispatches to the tenant dashboard',
    queryIds: ['Q-003'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F1-003',
    sourceAuthority: source.route,
    screenId: 'SCREEN-008',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'ACTIVE_MEMBER',
    behavior: 'Shell preserves tenant handle across governed navigation',
    queryIds: ['Q-003', 'Q-006', 'Q-007', 'Q-008'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F1-004',
    sourceAuthority: source.route,
    screenId: 'SCREEN-008',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'ACTIVE_MEMBER/GUEST',
    behavior: 'Logout clears the authenticated session and organization routes return to login',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A1-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-010',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'NOT_VIEWER',
    behavior: 'Populated Dashboard settles with canonical KPIs and navigation',
    queryIds: ['Q-021a', 'Q-021b', 'Q-050', 'Q-051', 'Q-052', 'Q-053', 'Q-054', 'Q-055'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-011',
    routeId: 'ROUTE-010',
    roleOrRoleClass: 'ALL',
    behavior: 'Product list renders canonical data with prefix search',
    queryIds: ['Q-011', 'Q-015'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-012',
    routeId: 'ROUTE-011',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Create-product route and form are reachable through the governed action',
    queryIds: ['Q-016'],
    commandIds: ['C-09'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-013',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'ALL',
    behavior: 'Product detail renders zero-stock store rooms and gated tabs/actions',
    queryIds: ['Q-014', 'Q-017', 'Q-018'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A3-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-014',
    routeId: 'ROUTE-014',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Categories render canonical reference data',
    queryIds: ['Q-016'],
    commandIds: ['C-35a', 'C-35b'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A3-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-015',
    routeId: 'ROUTE-015',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Warehouses render canonical reference data',
    queryIds: ['Q-017', 'Q-058'],
    commandIds: ['C-12', 'C-36', 'C-37'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A5-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-017',
    routeId: 'ROUTE-016',
    roleOrRoleClass: 'NOT_VIEWER',
    behavior: 'Movement History renders the immutable canonical ledger and bounded product search',
    queryIds: ['Q-015r', 'Q-022', 'Q-083'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C13-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-042',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Opening balance accepts frozen zero quantity and creates its result through C13',
    queryIds: ['Q-014', 'Q-017', 'Q-018'],
    commandIds: ['C-13'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C14-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-016',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Adjustment changes isolated stock through C14',
    queryIds: ['Q-018'],
    commandIds: ['C-14'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C33-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-053',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Transfer updates both isolated store-room balances through C33',
    queryIds: ['Q-018'],
    commandIds: ['C-33'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A7-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-018/019/020',
    routeId: 'ROUTE-022/023/024/025',
    roleOrRoleClass: 'PARTNER_WRITERS',
    behavior: 'Supplier, buyer, and partner detail data settle with open/history sections',
    queryIds: ['Q-031', 'Q-032', 'Q-039', 'Q-040'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C38-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-020',
    routeId: 'ROUTE-023',
    roleOrRoleClass: 'PARTNER_WRITERS',
    behavior: 'An isolated private partner deactivates and restores through C38',
    queryIds: ['Q-032', 'Q-080'],
    commandIds: ['C-38'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A8-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-021/022',
    routeId: 'ROUTE-017/018',
    roleOrRoleClass: 'PO_READERS/PO_WRITERS',
    behavior: 'PO list search and private draft builder are reachable',
    queryIds: ['Q-033', 'Q-084a', 'Q-084b'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C15-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-023',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'An isolated draft transitions to Ordered through C15',
    queryIds: ['Q-036', 'Q-037', 'Q-038'],
    commandIds: ['C-15'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C16-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-023',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'A different isolated order transitions to Cancelled through C16',
    queryIds: ['Q-036', 'Q-038'],
    commandIds: ['C-16'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Isolated partial receiving transitions through C17',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-002',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Isolated full receiving transitions through C17',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-003',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Over-receipt is rejected and remains on the receiving route',
    queryIds: ['Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  ...(
    [
      'OWNER',
      'ADMIN',
      'INVENTORY_MANAGER',
      'PROCUREMENT_MANAGER',
      'STOREKEEPER',
      'ANALYST',
      'VIEWER',
    ] as const
  ).map((role, index) => ({
    acceptanceId: `A10-RBAC-${String(index + 1).padStart(3, '0')}`,
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-010/011/017/018/021/024/029',
    routeId: 'ROUTE-009/010/016/017/020/022/030',
    roleOrRoleClass: role,
    behavior: `${role} receives representative allowed actions and explicit route denial evidence`,
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR' as const,
  })),
  {
    acceptanceId: 'A10-RSP-390',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024/043',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior:
      '390x844 read-only traversal has no page overflow and drawer actions remain reachable',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '390x844',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-RSP-1024',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior:
      '1024x768 read-only traversal has no page overflow and desktop navigation remains reachable',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1024x768',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-RSP-1280',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior: '1280x900 functional traversal also provides desktop layout evidence',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
];

export const acceptanceIds = new Set(acceptanceManifest.map((row) => row.acceptanceId));
