export interface AcceptanceRow {
  readonly acceptanceId: string;
  readonly sourceAuthority: string;
  readonly screenId: string;
  readonly routeId: string;
  readonly roleOrRoleClass: string;
  readonly behavior: string;
  readonly queryIds: readonly string[];
  readonly commandIds: readonly string[];
  readonly viewportRequirement: string;
  readonly evidenceType:
    'REAL_BROWSER' | 'REAL_BROWSER_REAL_EMULATOR' | 'BLOCKED_AUTHORITY_DEPENDENCY';
}

const source = {
  route: 'docs/ui-final/20_FINAL_NAVIGATION_LINK_AND_ROUTE_MAP.md',
  matrix: 'docs/frontend-execution-control-pack/04_ROUTE_SCREEN_FEATURE_MATRIX.md',
  query: 'docs/database-final/DB_04_FINAL_QUERY_INDEX_PAGINATION_REALTIME_CONTRACT.md',
  command: 'docs/frontend-execution-control-pack/08_COMMAND_AND_MUTATION_MAP.md',
  rbac: 'docs/frontend-execution-control-pack/09_ROLE_RBAC_UI_MAP.md',
  responsive: 'docs/frontend-execution-control-pack/10_RESPONSIVE_BEHAVIOR_MAP.md',
} as const;

export const acceptanceManifest: readonly AcceptanceRow[] = [
  {
    acceptanceId: 'A10-F1-001',
    sourceAuthority: source.route,
    screenId: 'SCREEN-001',
    routeId: 'ROUTE-001',
    roleOrRoleClass: 'PUBLIC',
    behavior: 'Public home renders and exposes governed auth links',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER',
  },
  {
    acceptanceId: 'A10-F1-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-003',
    routeId: 'ROUTE-003',
    roleOrRoleClass: 'ACTIVE_MEMBER',
    behavior:
      'Global login resolves membership from the authenticated UID and dispatches to the tenant dashboard',
    queryIds: ['Q-003'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F1-003',
    sourceAuthority: source.route,
    screenId: 'SCREEN-008',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'ACTIVE_MEMBER',
    behavior: 'Shell preserves tenant handle across governed navigation',
    queryIds: ['Q-003', 'Q-006', 'Q-007', 'Q-008'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F1-004',
    sourceAuthority: source.route,
    screenId: 'SCREEN-008',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'ACTIVE_MEMBER/GUEST',
    behavior: 'Logout clears the authenticated session and organization routes return to login',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A1-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-010',
    routeId: 'ROUTE-009',
    roleOrRoleClass: 'NOT_VIEWER',
    behavior: 'Populated Dashboard settles with canonical KPIs and navigation',
    queryIds: ['Q-021a', 'Q-021b', 'Q-050', 'Q-051', 'Q-052', 'Q-053', 'Q-054', 'Q-055'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-011',
    routeId: 'ROUTE-010',
    roleOrRoleClass: 'ALL',
    behavior: 'Product list renders canonical data with prefix search',
    queryIds: ['Q-011', 'Q-015'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-012',
    routeId: 'ROUTE-011',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Create-product route and form are reachable through the governed action',
    queryIds: ['Q-016'],
    commandIds: ['C-09'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A2-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-013',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'ALL',
    behavior: 'Product detail renders zero-stock store rooms and gated tabs/actions',
    queryIds: ['Q-014', 'Q-017', 'Q-018'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A3-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-014',
    routeId: 'ROUTE-014',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Categories render canonical reference data',
    queryIds: ['Q-016'],
    commandIds: ['C-35a', 'C-35b'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A3-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-015',
    routeId: 'ROUTE-015',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Warehouses render canonical reference data',
    queryIds: ['Q-017', 'Q-058'],
    commandIds: ['C-12', 'C-36', 'C-37'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A5-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-017',
    routeId: 'ROUTE-016',
    roleOrRoleClass: 'NOT_VIEWER',
    behavior: 'Movement History renders the immutable canonical ledger and bounded product search',
    queryIds: ['Q-015r', 'Q-022', 'Q-083'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C13-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-042',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Opening balance accepts frozen zero quantity and creates its result through C13',
    queryIds: ['Q-014', 'Q-017', 'Q-018'],
    commandIds: ['C-13'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C14-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-016',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Adjustment changes isolated stock through C14',
    queryIds: ['Q-018'],
    commandIds: ['C-14'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C33-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-053',
    routeId: 'ROUTE-012',
    roleOrRoleClass: 'INVENTORY_WRITERS',
    behavior: 'Transfer updates both isolated store-room balances through C33',
    queryIds: ['Q-018'],
    commandIds: ['C-33'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A7-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-018/019/020',
    routeId: 'ROUTE-022/023/024/025',
    roleOrRoleClass: 'PARTNER_WRITERS',
    behavior: 'Supplier, buyer, and partner detail data settle with open/history sections',
    queryIds: ['Q-031', 'Q-032', 'Q-039', 'Q-040'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C38-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-020',
    routeId: 'ROUTE-023',
    roleOrRoleClass: 'PARTNER_WRITERS',
    behavior: 'An isolated private partner deactivates and restores through C38',
    queryIds: ['Q-032', 'Q-080'],
    commandIds: ['C-38'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-A8-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-021/022',
    routeId: 'ROUTE-017/018',
    roleOrRoleClass: 'PO_READERS/PO_WRITERS',
    behavior: 'PO list search and private draft builder are reachable',
    queryIds: ['Q-033', 'Q-084a', 'Q-084b'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C15-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-023',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'An isolated draft transitions to Ordered through C15',
    queryIds: ['Q-036', 'Q-037', 'Q-038'],
    commandIds: ['C-15'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C16-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-023',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'A different isolated order transitions to Cancelled through C16',
    queryIds: ['Q-036', 'Q-038'],
    commandIds: ['C-16'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Isolated partial receiving transitions through C17',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-002',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Isolated full receiving transitions through C17',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-C17-003',
    sourceAuthority: source.command,
    screenId: 'SCREEN-024',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'Over-receipt is rejected and remains on the receiving route',
    queryIds: ['Q-036', 'Q-037'],
    commandIds: ['C-17'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  ...(
    [
      'OWNER',
      'ADMIN',
      'INVENTORY_MANAGER',
      'PROCUREMENT_MANAGER',
      'STOREKEEPER',
      'ANALYST',
      'VIEWER',
    ] as const
  ).map((role, index) => ({
    acceptanceId: `A10-RBAC-${String(index + 1).padStart(3, '0')}`,
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-010/011/017/018/021/024/029',
    routeId: 'ROUTE-009/010/016/017/020/022/030',
    roleOrRoleClass: role,
    behavior: `${role} receives representative allowed actions and explicit route denial evidence`,
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR' as const,
  })),
  {
    acceptanceId: 'A10-RSP-390',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024/043',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior:
      '390x844 read-only traversal has no page overflow and drawer actions remain reachable',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '390x844',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-RSP-1024',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior:
      '1024x768 read-only traversal has no page overflow and desktop navigation remains reachable',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1024x768',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-RSP-1280',
    sourceAuthority: source.responsive,
    screenId: 'SCREEN-010/011/013/017/018/021/024',
    routeId: 'ROUTE-009/010/012/016/017/020/022',
    roleOrRoleClass: 'OWNER',
    behavior: '1280x900 functional traversal also provides desktop layout evidence',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  // ─── Macro-B (F4/F5) acceptance rows ────────────────────────────────────
  {
    acceptanceId: 'A10-F4-NET-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-031',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Connected Businesses lists the ACTIVE Fresh Foods connection when Network is enabled',
    queryIds: ['Q-041'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-NET-002',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-031',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A role outside NETWORK_ROLES is denied Network routes before any query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-NET-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-031/028',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Disabling Network in Settings turns Network routes into 404, not 403; re-enabling restores access',
    queryIds: ['Q-006'],
    commandIds: ['C-02'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-DISC-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery blocks searching the caller’s own handle',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-DISC-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery reports no match for an exact unknown handle (no fuzzy search)',
    queryIds: ['Q-001'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-DISC-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-032',
    routeId: 'ROUTE-031',
    roleOrRoleClass: 'OWNER',
    behavior: 'Business discovery finds an exact-handle match and surfaces its directory card',
    queryIds: ['Q-001'],
    commandIds: ['C-18'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CONN-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-033',
    routeId: 'ROUTE-032',
    roleOrRoleClass: 'OWNER',
    behavior: 'Connection detail renders status, direction, and disable/catalog/mapping actions',
    queryIds: ['Q-034', 'Q-042', 'Q-043'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CAT-SUP-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-034/051',
    routeId: 'ROUTE-033',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Publishing an own product to the supplier catalog projects only the allowlisted fields',
    queryIds: ['Q-045'],
    commandIds: ['C-21'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CAT-SUP-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-034',
    routeId: 'ROUTE-033',
    roleOrRoleClass: 'OWNER',
    behavior: 'Unpublishing a supplier catalog item removes it from the published list',
    queryIds: ['Q-045'],
    commandIds: ['C-22'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CAT-BUY-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-035',
    routeId: 'ROUTE-034',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Buyer catalog lists a connected supplier’s published items and finds one by exact SKU',
    queryIds: ['Q-046'],
    commandIds: ['C-24'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-MAP-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-037',
    routeId: 'ROUTE-036',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Mappings list shows the VERIFIED mapping and states disabled mappings cannot be restored',
    queryIds: ['Q-043'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-MAP-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-036',
    routeId: 'ROUTE-035',
    roleOrRoleClass: 'OWNER',
    behavior: 'Mapping wizard refuses an unknown supplier SKU and an invalid conversion factor',
    queryIds: ['Q-047'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-MAP-003',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-036',
    routeId: 'ROUTE-035',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Mapping wizard creates a new VERIFIED mapping after semantic confirmation and a positive factor',
    queryIds: ['Q-011', 'Q-041', 'Q-047'],
    commandIds: ['C-25'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-MAP-004',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-037',
    routeId: 'ROUTE-036',
    roleOrRoleClass: 'OWNER',
    behavior: 'Disabling a mapping removes it from the active list with no restore action offered',
    queryIds: ['Q-043'],
    commandIds: ['C-26'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior:
      'Buyer submits an existing connected draft; C-34 line editing stays read-only throughout',
    queryIds: ['Q-036', 'Q-037', 'Q-038'],
    commandIds: ['C-27'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-002',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Buyer cancels an existing connected draft',
    queryIds: ['Q-036'],
    commandIds: ['C-31'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-003',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier accepts a SUBMITTED connected order',
    queryIds: ['Q-036'],
    commandIds: ['C-28'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-004',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier rejects a SUBMITTED connected order',
    queryIds: ['Q-036'],
    commandIds: ['C-28'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-005',
    sourceAuthority: source.command,
    screenId: 'SCREEN-039',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'Supplier ships an ACCEPTED order as a single full shipment',
    queryIds: ['Q-036'],
    commandIds: ['C-29'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-006',
    sourceAuthority: source.command,
    screenId: 'SCREEN-040',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior:
      'Buyer receives a SHIPPED connected order partially, then completes it, with supplier-unit conversion',
    queryIds: ['Q-017', 'Q-018', 'Q-036', 'Q-037'],
    commandIds: ['C-30'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-007',
    sourceAuthority: source.command,
    screenId: 'SCREEN-040',
    routeId: 'ROUTE-021',
    roleOrRoleClass: 'RECEIVERS',
    behavior: 'An over-receipt beyond the outstanding supplier quantity is blocked client-side',
    queryIds: ['Q-036', 'Q-037'],
    commandIds: ['C-30'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-TEAM-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-027',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Team screen protects the Owner row from role/suspend/remove actions available on other rows',
    queryIds: ['Q-009', 'Q-010'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-TEAM-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-027/050',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'OWNER',
    behavior: 'Owner invites a new user and the invite link is shown exactly once',
    queryIds: ['Q-009'],
    commandIds: ['C-07'],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-SET-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-028',
    routeId: 'ROUTE-028',
    roleOrRoleClass: 'OWNER',
    behavior: 'Owner has full Settings access including the Network feature toggle',
    queryIds: ['Q-006', 'Q-007', 'Q-017'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-SET-002',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-028',
    routeId: 'ROUTE-028',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A non-Owner/Admin role is denied Settings before any settings query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-NOTIF-001',
    sourceAuthority: source.query,
    screenId: 'SCREEN-026',
    routeId: 'ROUTE-029',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Notifications list renders and states mark-read is temporarily unavailable (authority-blocked)',
    queryIds: ['Q-004', 'Q-005'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-REPORT-001',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-048',
    routeId: 'ROUTE-030',
    roleOrRoleClass: 'OWNER',
    behavior:
      'Stock-on-hand report renders with filters, category subtotals, and a desktop CSV export control',
    queryIds: ['Q-061'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F5-REPORT-002',
    sourceAuthority: source.matrix,
    screenId: 'SCREEN-049',
    routeId: 'ROUTE-030',
    roleOrRoleClass: 'STOREKEEPER',
    behavior:
      'PO report renders its table for an authorized role and is denied before query for Storekeeper',
    queryIds: ['Q-062'],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
  {
    acceptanceId: 'A10-F4-CPO-BLOCKED-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-038',
    routeId: 'ROUTE-019',
    roleOrRoleClass: 'PO_WRITERS',
    behavior: 'F4-T03e C34 connected draft-line persistence',
    queryIds: [],
    commandIds: ['C-34'],
    viewportRequirement: '1280x900',
    evidenceType: 'BLOCKED_AUTHORITY_DEPENDENCY',
  },
  {
    acceptanceId: 'A10-F5-NOTIF-BLOCKED-001',
    sourceAuthority: source.command,
    screenId: 'SCREEN-026',
    routeId: 'ROUTE-029',
    roleOrRoleClass: 'OWNER',
    behavior: 'F5-T02 Notification mark-read',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'BLOCKED_AUTHORITY_DEPENDENCY',
  },
  {
    acceptanceId: 'A10-F5-TEAM-003',
    sourceAuthority: source.rbac,
    screenId: 'SCREEN-027',
    routeId: 'ROUTE-027',
    roleOrRoleClass: 'STOREKEEPER',
    behavior: 'A non-Owner/Admin role is denied Team before any team query fires',
    queryIds: [],
    commandIds: [],
    viewportRequirement: '1280x900',
    evidenceType: 'REAL_BROWSER_REAL_EMULATOR',
  },
];
export const acceptanceIds = new Set(acceptanceManifest.map((row) => row.acceptanceId));
